apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3100
        hostPort: 3100
        protocol: TCP
  - role: worker
  - role: worker

