apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 3100
    protocol: TCP
    listenAddress: "0.0.0.0"
- role: worker
- role: worker

