apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comedy-ing
  namespace: api-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /comedy
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80
